### ISSUE TITLE
SUB: Error deleting a sub on Mac and part of Linux

### ISSUE THREAD

**Issue by ukdtom** [ukdtom/WebTools.bundle#280]
`CRITICAL (logs:149) - Fatal error happened in Logs show: bad argument type for built-in operation (most recent call last):
  File "/Users/thepanders/Library/Application Support/Plex Media Server/Plug-ins/WebTools.bundle/Contents/Code/logs.py", line 137, in show
    with io.open(file, 'r', errors='ignore') as content_file:
TypeError: bad argument type for built-in operation`

Sadly has to wait until I can get my hands on a Mac, since it works nicely on Linux, so suspect a diff in Plex framework here on the different platforms

**Comment by jorgeserna** [comment]
Fixed this on Mac by adding the b type to the open action:

`with io.open(fileName, 'rb') as f:`

I don't know why this is needed since a XML file is a text file by definition, but apparently python in Mac sees it as binary.

**Comment by ukdtom** [comment]
Thanks for this input.

**Comment by ukdtom** [comment]
And fixed on WT V3 as well

**Comment by triantos** [comment]
It looks like you fixed this in August, but the version of WT 3.0.0 I have appears to still have this bug. I get the same error, and the error goes away if I edit DelFromXML()'s Non-OSX (else) clause to
`with io.open(fileName, 'rb') as f:`. Should this fix be in the 3.0.0 release? Or do I need to install some other branch?

**Comment by ukdtom** [comment]
Currently, due to the way that the Framework works on Mac, I had to disable it on that platform, since I also had issues with editing the XML files :(

Ref: https://github.com/ukdtom/WebTools.bundle/issues/420

**Comment by triantos** [comment]
Hi Tommy, this was in the else (non-Mac) clause. I run PMS and WebTools on FreeBSD.

Thanks,
-Nick

**Comment by ukdtom** [comment]
Ups....missed that part ;)

And you are correct here....

I "fixed" two out of tree :(

https://github.com/ukdtom/WebTools.bundle/blob/master/Contents/Code/pmsV3.py#L1190

**Comment by ukdtom** [comment]
Sadly, dev work has been put on hold, due to plugins been discontinued by Plex

Ref: https://www.plex.tv/blog/subtitles-and-sunsets-big-improvements-little-housekeeping/

No new versions will be release, and this project has been put on hold

UAS will still be maintained for as long as it lasts
