### ISSUE TITLE
PlayLists and ITunes

### ISSUE THREAD

**Issue by ukdtom** [ukdtom/WebTools.bundle#367]
Seems like when a Playlist on PMS came from iTunes, that it breaks the Playlist module

@trumpy81 Got link to a manual about how to import a playlist from iTunes?

/T

**Comment by trumpy81** [comment]
No manual ... the iTunes playlist import is a function of PMS. When you have iTunes installed on a PC/Mac and if your preferences are turned on, then installing PMS automatically imports iTunes and it's playlists.

For the Syno and Linux it's all manual, you have to modify the iTunes Music Library.xml and then import that into Plex.

I have instructions on doing that at Q24 on the Synology FAQ's page.

https://forums.plex.tv/discussion/191000/faqs-read-this-first?new=1

**Comment by ukdtom** [comment]
Thanks....I'll look into it

**Comment by ukdtom** [comment]
@Andy
I need you to do something for me here:

Browse to: PMS:32400/playlists/all?X-Plex-Token=YOUR_TOKEN

That should list your playlists
In that list, there's a key element like:
key="/playlists/21641/items"

Then browse to: PMS:32400"INSERT_KEY_FROM_ABOVE"?X-Plex-Token=YOUR_TOKEN

That should show an XML with your playlist...
So please Copy/Paste that in here, so I can see how it looks for an iTune playlist

**Comment by trumpy81** [comment]
I followed your instructions and saved the results for each step in the two xml/text files attached below.

[Results1.xml.txt](https://github.com/ukdtom/WebTools.bundle/files/1220670/Results1.xml.txt)
[Results2.xml.txt](https://github.com/ukdtom/WebTools.bundle/files/1220671/Results2.xml.txt)

**Comment by ukdtom** [comment]
You're the man, thanks

**Comment by ukdtom** [comment]
@trumpy81 

Could you reproduce, and then upload WT logs?

**Comment by trumpy81** [comment]
Done!!

I should note that the iTunes playlists causing the problem are smart playlists. Attempting to download the playlist (by clicking on the download button in the Playlist module) causes the page to go blank with a white backround. Only way to recover is to close the page and then launch WebTools again.

Logs: 
[WebTools Logs.zip](https://github.com/ukdtom/WebTools.bundle/files/1524874/WebTools.Logs.zip)

**Comment by ukdtom** [comment]
Seems like a size issue, according to the logs....
Result1.txt file indicated, that it contained 4873 items, so need to grap in smaller chunks I guess...

Darn

**Comment by ukdtom** [comment]
And reproduced with a playlist of +6000 tv episodes

**Comment by ukdtom** [comment]
@trumpy81 

Translate build updated, so we now should be able to download the darn thing.....

But when said, import also can't handle such a big list, so continue to work on that, but if you could test download, it would be great

**Comment by trumpy81** [comment]
Downloaded and installed latest translation build.

The smart playlist downloaded without causing a crash (👍), but after checking the file, only the first few lines are saved.

This is what is saved within the downloaded file.
#EXTM3U
#Written by WebTools for Plex
#Playlist name: 90’s Music
#Playlist type: audio
#Server Id: 417b9d040e8177c77dd6b98279a1e2a7dd4d0eb9

This may cause some concerns, because those who do not know, might think this is a working playlist when it is not.

If there is a way to identify smart playlists, maybe it would be better to not download them and popup a message to let the user know?

**Comment by ukdtom** [comment]
Logs please

**Comment by trumpy81** [comment]
Done!

[WebTools Logs.zip](https://github.com/ukdtom/WebTools.bundle/files/1534281/WebTools.Logs.zip)

**Comment by ukdtom** [comment]
Hi @trumpy81 

I made a mistake here, sorry...it was hard coded for video based playlists...

When said, I also optimized the way it does suff, so should work now, but when said, changed the format as well, so the downloaded playlists sadly can't be imported currently, but would love for you to confirm if you can download now?

It's in a special branch, due to me been a bit under pressure here with changing the format, so close to the cutoff time, so please download this:
https://github.com/ukdtom/WebTools.bundle/archive/Tommy-367.zip

And please respond ASAP, and if still not working, logs please

**Comment by trumpy81** [comment]
Tested and downloading is working. I attempted to import it, but got a message informing me that it already existed, as expected.

I also renamed and edited the downloaded file and attempted to import it, but I got this error:
Error: playlistService.importPlaylist - Exception happened in Playlist import was: list index out of range

I guess that is expected also?

**Comment by ukdtom** [comment]
Yep, and thanks so far

As Arnold said: "I'll be back"

**Comment by ukdtom** [comment]
Care to re-download and apply our "special" branch, and then check if export/import works now?
https://github.com/ukdtom/WebTools.bundle/archive/Tommy-367.zip

And if still not, logs please

**Comment by trumpy81** [comment]
Well, you cocked that up didn't you ... Not only can I download it, I can edit it and import it as well ... shame on you ... lol

**Comment by ukdtom** [comment]
Thanks mate
